# Generated by Django 2.2.10 on 2021-06-12 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterHigh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ch', max_length=256)),
                ('counts', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CounterLow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='cl', max_length=256)),
                ('counts', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CounterMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='cm', max_length=256)),
                ('counts', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='todoitem',
            options={},
        ),
        migrations.AddField(
            model_name='category',
            name='todos_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='category',
            field=models.ManyToManyField(blank=True, default=1, to='tasks.Category'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='doH',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.CounterHigh'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='doL',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.CounterLow'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='doM',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.CounterMedium'),
        ),
    ]
